### ISSUE TITLE
Support for s3-compatible storage systems?

### ISSUE THREAD

**Issue by sundowndev** [ulule/gostorages#16]
Hi, I'd like to use this interface with DigitalOcean's s3 compatible object storage. I guess this is not possible using aws sdk directly, so I think this would be a cool feature to have.

EDIT: This can be done using the minio's SDK https://github.com/minio/minio-go

**Comment by sundowndev** [comment]
See my implementation of the minio client based on your interface https://github.com/dreamvo/gilfoyle/blob/4afb172dd1e90081459db4f336f868982d977b83/storage/s3/s3.go

**Comment by thoas** [comment]
supported via `endpoint`
